[package]
name = "tplinker"
version = "0.1.0"
authors = ["Rob Young <rob@robyoung.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
